### ISSUE TITLE
[Idea/Suggestion] Playing Direct Links

### ISSUE THREAD

**Issue by Ameno-Sagiri** [pixeltailgames/gm-mediaplayer#11]
Would it be possible for Media Player to support direct urls, such as direct mp4/avi etc links through Copy or Dropbox? It just seems to me that if it can support actual services, it would be able to support barebones web videos.

If not, could you tell me why I'm horrifically wrong <:^)

**Comment by samuelmaddock** [comment]
Direct web links are supported for a few different media types like png, jpg, gif, and webm. However, not all codecs are supported by Awesomium which is why mp4/avi isn't available. They probably won't ever be available in GMod because they're proprietary formats which require licensing.
