### ISSUE TITLE
Opening menu on E?

### ISSUE THREAD

**Issue by kpjVideo** [pixeltailgames/gm-mediaplayer#3]
Would this be an option in the future?
I've tried using the OpenRequestMenu in the shared (ENT:Use function) of the mediaplayer_base but couldn't get it to work.
Any ideas?

**Comment by samuelmaddock** [comment]
I don't have any plans to implement this feature into the addon, but it would be possible by creating a new entity that uses `mediaplayer_base` as its base entity. Here's some code (untested) that would use the behavior you've described:

```lua
ENT.base = "mediaplayer_base"

if SERVER then
	util.AddNetworkString("OpenReqMenu")

	function ENT:Use( ply )
		net.Start("OpenReqMenu")
			 net.WriteEntity(self)
		net.Send(ply)
	end
else
	net.Receive("OpenReqMenu", function()
		local ent = net.ReadEntity()
		MediaPlayer.OpenRequestMenu(ent)
	end)
end
```

**Comment by kpjVideo** [comment]
Here's the full error I received (Note: The menu does pop up, however the mediaplayer doesn't turn on and the menu doesn't enable the cursor):
[ERROR] addons/gm-mediaplayer-master/lua/mediaplayer/controls/dmediaplayerreques
t.lua:84: attempt to index local 'mp' (a nil value)
  1. GetServiceIDs - addons/gm-mediaplayer-master/lua/mediaplayer/controls/dmedi
aplayerrequest.lua:84
   2. SendServices - addons/gm-mediaplayer-master/lua/mediaplayer/controls/dmedi
aplayerrequest.lua:92
    3. SetMediaPlayer - addons/gm-mediaplayer-master/lua/mediaplayer/controls/dm
ediaplayerrequest.lua:101
     4. OpenRequestMenu - addons/gm-mediaplayer-master/lua/mediaplayer/cl_init.l
ua:253
      5. func - addons/gm-mediaplayer-master/lua/entities/mediaplayer_example/sh
ared.lua:22
       6. unknown - lua/includes/modules/net.lua:32

**Comment by kpjVideo** [comment]
Any ideas?

**Comment by samuelmaddock** [comment]
Sorry, I got caught up with other things. The issue has to do with the media player not existing on the client when it receives the net message. This is what the previous `ENT:Use()` function  managed.

When do you want clients to see the TV? If it should always be visible, try adding the following code:
```lua
if SERVER then
    function ENT:Initialize()
        self.BaseClass.Initialize( self )

        local mp = self:GetMediaPlayer()
        mp._TransmitState = TRANSMIT_ALWAYS
    end
end
```

**Comment by kpjVideo** [comment]
ahh no problem, sorry for not clarifying. Basically I'm looking for the TV menu to (on use) open the menu for the person who pressed E on it and plays the video for anyone that also presses E on it.

Thanks :)

**Comment by kpjVideo** [comment]
after adding that I seem to get this, this time the ENT spawns with the ability to walk through it, I've tried using SetModel and SetMoveType + Wake however nothing seemed to work.

This is the error I get when spawning one:
[ERROR] addons/gm-mediaplayer-master/lua/entities/mediaplayer_example/shared.lua
:16: attempt to index local 'mp' (a nil value)
  1. unknown - addons/gm-mediaplayer-master/lua/entities/mediaplayer_example/sha
red.lua:16
   2. Spawn - [C]:-1
    3. SpawnFunction - gamemodes/base/entities/entities/base_entity/init.lua:77
     4. Spawn_SENT - gamemodes/sandbox/gamemode/commands.lua:619
      5. unknown - gamemodes/sandbox/gamemode/commands.lua:686
       6. unknown - lua/includes/modules/concommand.lua:69

**Comment by kpjVideo** [comment]
sorry for the rush, any more ideas on what I should do?
