### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ForeverButthurt** [pixeltailgames/gm-mediaplayer#4]
Buttons pause/resume and seek don't work on youtube service.

**Comment by samuelmaddock** [comment]
Are you using the entity right-click menu? I created a much nicer sidebar menu, but I have it commented out here: https://github.com/pixeltailgames/gm-mediaplayer/blob/master/lua/mp_menu/sidebar.lua#L204-L205

Uncomment the two lines and change the `KEY_` enums to [whatever you want](http://wiki.garrysmod.com/page/Enums/KEY).

**Comment by samuelmaddock** [comment]
Looks like the JavaScript code isn't able to interact with the YouTube player since it's likely using the HTML5 version now instead of Flash. I'll see what I can do to fix this.

**Comment by samuelmaddock** [comment]
I changed the YouTube service to use the [IFrame Player API](https://developers.google.com/youtube/iframe_api_reference) instead of directly loading the YouTube page. The issues you were experiencing should be fixed.
