### ISSUE TITLE
Problems with Twitch service

### ISSUE THREAD

**Issue by ForeverButthurt** [pixeltailgames/gm-mediaplayer#5]
Pause button and volume control don't work on twitch service.
P.S. Yes I use your sidebar menu, and sorry for trouble.

**Comment by samuelmaddock** [comment]
Last time I checked, Twitch doesn't have any JavaScript interface on their
player to toggle playback or change the volume. With that said, I don't
think there's a good fix for this outside of making the user manually
interact with the Twitch player.

**Comment by samuelmaddock** [comment]
Looks like they actually support pausing and seeking now, but still no volume control. :-1: 
https://github.com/justintv/Twitch-API/blob/master/player.md#functions

Wyozi, another GMod developer, has created an issue for this: justintv/Twitch-API#337

**Comment by samuelmaddock** [comment]
Closing this since it's unlikely to ever be fixed unless GMod devs replace Awesomium such that Twitch's new HTML5 player will work.
